###
POST http://127.0.0.1:8000/convert/pdf-to-png
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
------WebKitFormBoundary--

###
POST http://127.0.0.1:8000/convert/png-to-pdf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
------WebKitFormBoundary--

###
POST http://127.0.0.1:8000/convert/png-to-jpeg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
------WebKitFormBoundary--

###
POST http://127.0.0.1:8000/convert/jpeg-to-png
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
------WebKitFormBoundary--

###
POST http://127.0.0.1:8000/convert/pdf-to-jpeg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.pdf"
Content-Type: application/pdf

< ./example.pdf
------WebKitFormBoundary--

###
POST http://127.0.0.1:8000/convert/jpeg-to-pdf
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

< ./example.jpg
------WebKitFormBoundary--